### ISSUE TITLE
when processing lots of messages canceling is futile [bug]

### ISSUE THREAD

**Issue by mandric** [ushahidi/SMSSync#125]
there is a loop that cannot be broken out of when sending many messages.  smssync warns but canceling does nothing to the loop, pretty sure we want to be able to break out of that loop.

to reproduce, queue up a hundred or so message in your tasks checker, then turn on smssync to poll the task.

log entry:

```
I/ProcessSms( 1343): postToSentBox(): post message to sentbox
I/org.addhen.smssync.util.Util( 1343): processMessages(): Process text messages as received from the user's phone
```

![screen shot 2013-09-20 at 2 46 38 pm](https://f.cloud.github.com/assets/25641/1183342/f6b8b5de-222d-11e3-831e-0cefad5e02c7.png)

**Comment by eyedol** [comment]
@mandric closing this issue. Feel free to reopen if it still happens
