### ISSUE TITLE
fail to get data through http post

### ISSUE THREAD

**Issue by emollusion** [ushahidi/SMSSync#147]
I have been working back and forth with the log in smssync for a while now but seems to get stuck at the same place.

I cant get any data when using post.

Example of line:
if(isset($_POST['secret'])){$secret = $_POST['secret'];}

And in the smssync config it has the same spelling, use of POST and JSON.

PHP error is undefined variable, and in the JSON output error message is 'no secret'.

I am lost...

Phone is Fairphone 1, android 4.2.2
Smssync is latest fr play store.

Server is Lighttp and php under android, so running the server locally on the phone.

Smssync still needs to be connected to the internet to try to sync locally, which is sad but not really a problem.

Any help?

**Comment by kizomanizo** [comment]
You were quite a bully

**Comment by jesseperexc** [comment]
What

**Comment by kizomanizo** [comment]
I commented on a 4 year old thread. Landed on it as I was looking on a proper JSON schema to test get_messace method.
