### ISSUE TITLE
Debug & Alerts

### ISSUE THREAD

**Issue by eyedol** [ushahidi/SMSSync#160]
As improvement to the logging feature, we need a way to interact with SMSSync via SMS by sending simple keywords to SMSSync. Based on the received keyword, SMSSync will send a response back to the sender. This will enable remote debugging to figure out what might be wrong with the phone/server. Here are sample keywords with responses.
Admin sends `sms` to phone running `SMSSync`

**Status**
1. `Is cell reception ok` gets a response `cell reception ok` otherwise no response from SMSSync which means there is something wrong. We can use the [PhoneStateListener](http://developer.android.com/reference/android/telephony/PhoneStateListener.html) API for this.
2. `Is server ok` gets a response `server responded with <200>` otherwise sends a reponse `cannot reach server`. Once SMSSync receives the `sms` it will make a request to the server.
3. `battery level` gets a response `battery level is <10%>` otherwise no response from SMSSync which means phone is dead.
4. `get status` gets all of the above responses as a single `sms`

**Alerts**
1. If battery level drops below 10% 
   1. post alert to server
   2. send alert text to stored phone number
1. If an SMS fails to send (due to credit, cell coverage, or bad number)
   1. post alert to server
2. If data connection is lost for extended time (either WiFi, or GSM)
   1. send alert SMS to stored phone number
### Status

To mitigate the issue of having to type a long sentence to query for status response from the phone or the potential of a normal message triggering a status query, it should use an @ prefix and a code instead. See comment by @browndav.

The table below list the query codes, the query, the query's positive and negative responses.

| Query code @xx | Query | \+ Query response | \- Query response |
| --- | --- | --- | --- |
| `@10` | `Is cell reception ok` | `cell reception ok` | The phone sends no response. |
| `@20` | `Is server ok` | `server responded with <HTTP Status Code> status code` eg. `server responded with 200 status code` | `Cannot reach server` |
| `@30` | `battery level` | `battery level is <percentage of battery level>` . eg. `battery level is 10%` | The phone sends no response. |
| `@40` | `get status` | all the query's positive responses | all the query's negative responses |

The query codes sent as SMS shouldn't be sent to the configured `Sync URL`
#### Scenario 1

If battery level of the device running SMSSync drops below 10%, SMSSync will make an HTTP GET request to the server with the following query params.
`?task=alert&message=battery level is at <percentage of battery level>`

At the same time, SMSSync will send SMS with the message `battery level is at <percentage of battery level>` to a phone number that has been configured at the Settings screen to receive alerts. For now it should be only one phone number and cannot be the phone number of the device.
#### Scenario 2

If SMSSync failed to send SMS due to error reported by [sendMultipartTextMessage](http://developer.android.com/reference/android/telephony/SmsManager.html#sendMultipartTextMessage%28java.lang.String, java.lang.String, java.util.ArrayList<java.lang.String>, java.util.ArrayList<android.app.PendingIntent>, java.util.ArrayList<android.app.PendingIntent>%29) make an HTTP GET request to the server with the following query params. `?task=alert&message=<error message>` See http://developer.android.com/reference/android/telephony/SmsManager.html for the error messages.
#### Scenario 3

If data connection is lost for extended time (either WiFi, or GSM)
Send SMS with the message `No data connection on the device` to the configured phone number.

**Comment by mpandi** [comment]
After an SMS has been synced..I am not bale to delete from the phone...0 messages deleted
