### ISSUE TITLE
No sync

### ISSUE THREAD

**Issue by alejobd** [ushahidi/SMSSync#181]
I have followed the instructions to configure smssync, but I can't get it to sync.
Details:
1) Activated the SMSSync plugin in my ushahisi website. No secret
2) Installed the SMSSync app in my Android smartphone.
3) Added my sync URL, using the URL indicated in the in the ushahisi's SMSSync plugin's settings page (https://sitename.crowdmap.com/smssync). Used a keyword.
4) Enabled it, and started the SMSSync service
5) Sent a message to the phone, containing the keyword
6) The SMS appears in the "Pending" section
7) Whenever I try to sync, manually. I get this message:
     "Successfully processed 1 item, 0 syncd, 1 failed"
8) The log (I activated it to troubleshoot) shows:
     "Sending message to the server failed. Server error: Server returned HTTP status code of 200."

Tested with 2 smartphones, same results. Android 4.2.1 in one. Not sure about the version of the other one right now (Android 4, at least).
Both phone numbers are noted in ushahisi's Settings-->SMS (I presume that it is not mandatory, but just in case).

On an unrelated note, I tried to send this problem using the forums (https://forums.ushahidi.com), but they are buggy as hell: one day they don't work (last Thursday), today I try to login with my Google account, but get this error:
"SSL received a record that exceeded the maximum permissible length. (Error code: ssl_error_rx_record_too_long)", then I try to create a new account, but never receive my confirmation email (tried resending, without much success)... If you happen to be in touch with the forum's admin, let him know.

**Comment by kiplagat** [comment]
am also having the same error

**Comment by sorinpohontu** [comment]
Seems to me like an error on webserver response.
@eyedol I think you can close this issue for 2.8.0.
