### ISSUE TITLE
Only first set of sync rules work

### ISSUE THREAD

**Issue by redbullpeter** [ushahidi/SMSSync#199]
When I defined two or more sets of Sync URL rules, only the first active rule works. See the following scenarios that work and don't work:
___
Sync rule 1 (Active) - works
Sync rule 2 (Active) - does not work
___
Sync rule 1 (Inactive) - inactive
Sync rule 2 (Active) - works
___
Sync rule 1 (Active) - works
Sync rule 2 (Inactive) - inactive
___
Sync rule 1 (Active) - works
Sync rule 2 (Active) - does not work
Sync rule 3 (Active) - does not work
___
Sync rule 1 (Inactive) - inactive
Sync rule 2 (Active) - works
Sync rule 3 (Active) - does not work
___
Sync rule 1 (Active) - works
Sync rule 2 (Inactive) - inactive
Sync rule 3 (Active) - does not work
___
Sync rule 1 (Inactive) - inactive
Sync rule 2 (Inactive) - inactive
Sync rule 3 (Active) - works
___
The behaviour observed is that, the first active rule works as expected. The subsequent rules do not work and the message is in pending state. As soon as the first active rule is deactivated, the next rule (which is now first) instantly works and the subsequent rules don't work.

Version I am using is 2.6.1

The problem appears to be independent of the make, model and android version.

**Comment by sorinpohontu** [comment]
@eyedol I thin you can close this issue for 2.8.0.
