### ISSUE TITLE
Result request interval in 2.7.1

### ISSUE THREAD

**Issue by shtrih** [ushahidi/SMSSync#222]
Are there any issues about separate requests with `?task=result`? How often does SmsSync make this request? I set task check enabled with 1 minute frequency. Every minute I get requests to `?task=send` but none to task `result`. I got just one such request and don't know which event caused it.

**Comment by eyedol** [comment]
@shtrih no response. I'm assuming it's fixed. Feel free to re-open this if you experience this in latest stable release on the Playstore or the pre-releases.
