### ISSUE TITLE
incoming sms not auto syncing

### ISSUE THREAD

**Issue by jay-codes** [ushahidi/SMSSync#227]
SMSSync does not sync all incoming sms to the syncURL. i tried using it with and without keyword and it wont work. but when i load all inbox messages using the import button in the pending section, it imports and syncs all sms in my phone.

i only want it to new sync incoming sms, not all past sms in my phone.

please advise/

**Comment by mayreeh** [comment]
Hey I wish to ask for help in synchronizing smssync with pesapi, currently smssync not synchronizing, and log is empty.
