### ISSUE TITLE
Unsafe HTTPS use

### ISSUE THREAD

**Issue by wolfmd** [ushahidi/SMSSync#228]
This may be due to the results of other issues, but running a security scan against the source code of this project has shown that the HTTPS used in this application has been manually overiden. Using HTTPS increases the security of credentials transmitted between the device and server as well as guaranteeing there is no middle-man attacker feeding malicious data to the user.

It seems some of these are user-overrides of validation, however, EasySSLSocketFactory should not be used as a default.

ushahidiSMSSync/smssync/src/main/java/org/addhen/smssync/net/EasySSLSocketFactory.java:63:  SSLSocket created without proper hostname verification
ushahidiSMSSync/smssync/src/main/java/org/addhen/smssync/net/TrustedSocketFactory.java:52:  Custom HostnameVerifier used; this is not safe for production use
ushahidiSMSSync/smssync/src/main/java/org/addhen/smssync/net/TrustedSocketFactory.java:53:  AllowAllHostnameVerifier used, this is not a secure connection
ushahidiSMSSync/smssync/src/main/java/org/addhen/smssync/net/TrustedSocketFactory.java:76:  SSLSocket created without proper hostname verification

**Comment by alxndrsn** [comment]
Is this still an issue?  It doesn't look like any of the referenced classes still exist in the project, and HTTPS connections are now handled by third party libs.

**Comment by timmwille** [comment]
can be closed?

**Comment by wolfmd** [comment]
Yeah, for sure. Cheers!
