### ISSUE TITLE
SMS is queued, but not Sent

### ISSUE THREAD

**Issue by sorinpohontu** [ushahidi/SMSSync#230]
Hello.

I'm trying to implement SMSsync (v2.7.3) in my own application using documentation from Developer section and I have some issues.

I'm trying to Send SMS from my application and everything works quite well until I "Enable Message Results API" (see below).

If "Enable Message Results API" is unchecked, the SMS is sent.

If "Enable Message Results API" is checked, the messages are queued, but they are not actually sent. Here is relevant part from the log:

19-01 15:55 TaskCheckResponse: SmssyncResponse{payload=Payload{messages=[Message{message='Test 1', to='+40xxxxxxxxx', timestamp='null', uuid='2568c37b-00a4-4753-a014', mMessageType=0, mSentResultCode=-2, mSentResultMessage='', mDeliveryResultCode=-2, mDeliveryResultMessage='', mMessageList=[]}, Message{message='Test 2', to='+40xxxxxxxxx', timestamp='null', uuid='10a7c6de-047f-47e6-9b9f', mMessageType=0, mSentResultCode=-2, mSentResultMessage='', mDeliveryResultCode=-2, mDeliveryResultMessage='', mMessageList=[]}, Message{message='Test 3', to='+40xxxxxxxxx', timestamp='null', uuid='e736f0e1-252d-4403-adc9', mMessageType=0, mSentResultCode=-2, mSentResultMessage='', mDeliveryResultCode=-2, mDeliveryResultMessage='', mMessageList=[]}], task='send', secret='567890', error='null', success=false}}
19-01 15:55 SMSsync has completed processing this message.
19-01 15:55 Successfully finished performing task checking null
19-01 15:55 Checking scheduled message result services
19-01 15:56 Performing task checking
19-01 15:56 TaskCheckResponse: SmssyncResponse{payload=Payload{messages=[], task='send', secret='567890', error='null', success=false}} 

After "POST ?task=sent" I do receive the data:
{"queued_messages":["2568c37b-00a4-4753-a014","10a7c6de-047f-47e6-9b9f","e736f0e1-252d-4403-adc9"]}

I reply correctly on GET ?task=result with:
{"message_uuids":["2568c37b-00a4-4753-a014","10a7c6de-047f-47e6-9b9f","e736f0e1-252d-4403-adc9"]}

and I got the replay on POST ?task=result:
{"message_result":"[]"}

Note: on documentation the response should be "message_results", but actually is "message_result".

I've tried with "SMS Delivery Report" both enabled or disabled, same behavior.

Any clue ?

Have a nice day,
/Sorin

**Comment by eyedol** [comment]
Will look into this to see if it's producible. Your integration looks correct.

**Comment by sorinpohontu** [comment]
Hello. I've re-checked my code once again and made a test with your PHP sample.
With your code, everything works as expected, and the SMS is sent.

I've checked again and make sure the response output is always in JSON and now it seems it's working as expected. It's still a mystery why it wasn't working yesterday :)

Thanks for now, I'll get back if there will be another issue related to this.
