### ISSUE TITLE
Enable configuration of SMSSync through scanning of a QR code

### ISSUE THREAD

**Issue by arthurbuliva** [ushahidi/SMSSync#235]
As the title says, I think this will make it easy for people to configure SMSSync. Am thinking that this may be particularly useful for the Drupal module currently under test so that different users can get configuration details to either manually set up or Drupal generates a QR code which SMSSync will understand

**Comment by eyedol** [comment]
The QR code should embed the sample JSON below;
```json
{
    "sync_urls": [
        {
            "title": "Sync URL tilte",
            "secret_key": "123456",
            "keywords": [
                "word",
                "message",
                "title"
            ],
            "url": "http: //www.syncurl.com",
            "enabled": false
        },
        {
            "title": "Online SMS poll",
            "secret_key": "123456",
            "keywords": [],
            "url": "https: //www.online-polls.com/index.php",
            "enabled": true
        }
    ]
}
```

**Comment by arthurbuliva** [comment]
The Drupal 7 SMSSync module is waiting for you on this. It will give you a good means of testing whether the QR code scan actually works. https://github.com/arthurbuliva/smssync/commit/65aacd7b16a6bb47860e0ed195fdf31b797583b5

**Comment by eyedol** [comment]
@arthurbuliva mind attaching a sample QR code that has the sample JSON string above?

**Comment by arthurbuliva** [comment]
![snapshot7](https://cloud.githubusercontent.com/assets/302508/7245970/e2e7c954-e7fd-11e4-8a15-e30a661930d6.png)

**Comment by arthurbuliva** [comment]
{"sync_urls":[{"title":"localhost","secret_key":"123456","keywords":[],"url":"http://localhost/seven/smssync/listen","enabled":true}]}

**Comment by arthurbuliva** [comment]
![snapshot9](https://cloud.githubusercontent.com/assets/302508/7252126/a12d58f2-e83a-11e4-95fc-b05f1ba07e14.png)

**Comment by arthurbuliva** [comment]
Question, why do we need the "syncscheme" section? Normally the users don't configure any of those parameters in those sections, do they? The only thing that they configure is the device_id, which I have included in the QR code.

**Comment by eyedol** [comment]
@arthurbuliva the SyncScheme is a configuration option. There is a default one that is always set when you add a Sync URL. I thought it makes sense to provide that as well. Yes, this can be an optional field.
