### ISSUE TITLE
Setting the number of retries for a message

### ISSUE THREAD

**Issue by sorinpohontu** [ushahidi/SMSSync#237]
When sending a message and it will fail for various reasons, the message will be in Pending state for a undefined number of retries.

I'm thinking about adding in Settings a new variable for Number of retries for a message.
After specified number of retries is reached, the message should be deleted from Pending state.

Also, if "Message Results API" is enabled, it should respond to server in order to set it as Error and stop processing further.

**Comment by sorinpohontu** [comment]
Additional note: If the message fails, it should be send only once and after that, let the Message API (server side) to retry the message, if needed.

In this way, the logic in SMSSync should be easier to implement.

Looking forward for feedback.

**Comment by eyedol** [comment]
@sorinpohontu what will make the app not send the SMS? Wrong formatted phone number? There would be some edge cases where the phone number is correctly formatted but doesn't exist. If it's wrong formatted, I can just drop attempt at sending a SMS to it.

**Comment by sorinpohontu** [comment]
There might be various reasons:
* Wrong number format
* Number not exists
* Number is correct, but is not a GSM number
* Insufficient credit on SIM (for prepay numbers)
* No GSM coverage / signal

SMSSync will need to:
* Set the number of retries for a message (eg, try N times and after that do not send anymore)
* Or always send it once, and if it fails let the Response API (Server) to make a decision if it will be re-queued

Looking forward to hear from you.

**Comment by eyedol** [comment]
Still WIP. This is a tricky one because of the way we process SMSs. Still working on it.

**Comment by sorinpohontu** [comment]
Adding a new field in table 'messages', let's say message_no_of_retries would help.
After that, for send it's a just a simple query to select messages with `message_no_of_retries` <= Preferences.no_of_retries. After send, message_no_of_retries should be incremented and it will be not processed on next send.

In Message Result API, messages with message_no_of_retries >= Preferences.no_of_retries should be returned as not delivered (maybe a JOIN with sent_messages).

Please let me know if you need more info.

Looking forward to hear from you.

**Comment by eyedol** [comment]
@sorinpohontu  could you confirm this is fixed in [v2.8.0-rc.1](https://github.com/ushahidi/SMSSync/releases/tag/v2.8.0-rc.1)?

**Comment by sorinpohontu** [comment]
@eyedol Seems to work as expected, but I'll have to double check tomorrow and get back to you.

**Comment by sorinpohontu** [comment]
Settings: "No. of retries for pending message" = Three tries.
Actually, the message is sent 5 times. Can you recheck ?

**Comment by eyedol** [comment]
How many messages were in the queue? They got deleted after the 5th retries?

**Comment by sorinpohontu** [comment]
2 Messages, 1 correct and 1 wrong. The wrong message was deleted from Pending after 5th retry.
I've made another test with a single message in the queue, and the failed message has also 5 retries.
