### ISSUE TITLE
Message Results API scheduler is not started after phone shutdown/restart

### ISSUE THREAD

**Issue by sorinpohontu** [ushahidi/SMSSync#238]
I'm using "Message Results API", with Frequency check at 1 minute.

After device shutdown or reboot, the Message Results API scheduler is not started.

	24-01 16:20 The device has shutdown
	24-01 16:21 The device has rebooted
	24-01 16:21 Updated scheduler interval
	24-01 16:21 Updated scheduler interval
	24-01 16:21 Performing task checking
	24-01 16:21 TaskCheckResponse: SmssyncResponse{payload=Payload{messages=[], task='send', secret='567890', error='null', success=true}}
	24-01 16:21 Successfully finished performing task checking null
	24-01 16:21 There is active data connection
	24-01 16:21 Performing task checking
	24-01 16:21 TaskCheckResponse: SmssyncResponse{payload=Payload{messages=[], task='send', secret='567890', error='null', success=true}}
	24-01 16:21 Successfully finished performing task checking null
	24-01 16:22 Performing task checking
	24-01 16:22 TaskCheckResponse: SmssyncResponse{payload=Payload{messages=[], task='send', secret='567890', error='null', success=true}}
	24-01 16:22 Successfully finished performing task checking null 

In this case, I have to go to Settings, disable "Message Results API" and re-enabled it.

	24-01 16:25 TaskCheckResponse: SmssyncResponse{payload=Payload{messages=[], task='send', secret='567890', error='null', success=true}}
	24-01 16:25 Successfully finished performing task checking null
	24-01 16:25 SMSsync settings - [ Enter alert phone number ] has changed from [  ] to [  ]
	24-01 16:26 Performing task checking
	24-01 16:26 TaskCheckResponse: SmssyncResponse{payload=Payload{messages=[], task='send', secret='567890', error='null', success=true}}
	24-01 16:26 Successfully finished performing task checking null
	24-01 16:26 Stopping scheduler
	24-01 16:26 Scheduler stopped
	24-01 16:26 SMSsync settings - [ Enter alert phone number ] has changed from [  ] to [  ]
	24-01 16:26 SMSsync settings - [ Enter alert phone number ] has changed from [  ] to [  ]
	24-01 16:26 Message Results service started - interval: 60000
	24-01 16:26 Updated scheduler interval
	24-01 16:27 Performing task checking
	24-01 16:27 TaskCheckResponse: SmssyncResponse{payload=Payload{messages=[], task='send', secret='567890', error='null', success=true}}
	24-01 16:27 Successfully finished performing task checking null
	24-01 16:27 Checking scheduled message result services 

I have tried with both Quick Boot enabled and disabled, it's the same behavior.

**Comment by eyedol** [comment]
Could you confirm this is fixed in [v2.8.0-rc.1](https://github.com/ushahidi/SMSSync/releases/tag/v2.8.0-rc.1) ?

**Comment by sorinpohontu** [comment]
@eyedol Worked correctly in my latest tests, but I'll have to double check tomorrow and get back to you.

**Comment by sorinpohontu** [comment]
@eyedol Can you add the apk to 2.8.0-rc-1 release ? :)

**Comment by eyedol** [comment]
@sorinpohontu Added.

**Comment by sorinpohontu** [comment]
Seems that services are started after phone reboot on 2.8.0-rc-1. Great :)
