### ISSUE TITLE
Not working on localhost

### ISSUE THREAD

**Issue by mozaffari** [ushahidi/SMSSync#241]
I have a localhost server on my android named bitserver but all time the app says me that no data connection, It is not important to have a data connection on your localhost server.

**Comment by eyedol** [comment]
@mozaffari The phone can't reach the local web server. You should make sure they're both on the same network and that the phone can access localhost via a web browser. Use the webserver's IP address and make sure firewall is not block a port.

Closing. Let me know if it still persist.
