### ISSUE TITLE
Inconsistent results with Message Results API

### ISSUE THREAD

**Issue by sorinpohontu** [ushahidi/SMSSync#242]
When using Message Results API, message_result response varies, without a specific match to Developers documentation (http://smssync.ushahidi.com/developers).

1. sent_result_message is sometimes blank (?)
2. sent_result_code is -1 or -2 (on Developer page is 0 for success and -1 for error ?)
3. Strings messages are different from Documentation ("SMSsent" -> "SMSSync Message Sent").

Tested on v2.7.3 with Android: 4.1.1 and 4.2.2.

Please see the JSON responses below (with and without Delivery Notification):

	 {"message_result": "[
		{"sent_result_message":"SMS sent","delivered_result_message":"","uuid":"4a4598bd-a6e7-11e4-aac1-2a042924705f","sent_result_code":-1,"delivered_result_code":-2},
		{"sent_result_message":"","delivered_result_message":"","uuid":"4dd4895c-a6e7-11e4-aac1-2a042924705f","sent_result_code":-2,"delivered_result_code":-2},
	]"}

	{"message_result": "[
		{"sent_result_message":"SMS sent","delivered_result_message":"SMS delivered","uuid":"a421cd7e-a71d-11e4-aac1-2a042924705f","sent_result_code":-1,"delivered_result_code":-1},
		{"sent_result_message":"SMS sent","delivered_result_message":"","uuid":"a45c2ccd-a71d-11e4-aac1-2a042924705f","sent_result_code":-1,"delivered_result_code":-2},
	]"}

Have a nice day,
/Sorin

**Comment by lman817** [comment]
I'm experiencing the same issue: messages are being sent correctly but returning a -1 or -2 sent code. The -1 code is sensible, since that's the Android RESULT_OK code, but the -2 is just the default code assigned in SMSSync which for some reason is not being overridden by the correct code.

**Comment by eyedol** [comment]
Fixed

**Comment by sorinpohontu** [comment]
Great. Thanks :)
