### ISSUE TITLE
Message Results API stops functioning, randomly(?)

### ISSUE THREAD

**Issue by ghost** [ushahidi/SMSSync#244]
I've experienced a repeated bug where the message results API will stop functioning after SMSSync is up but inactive. Message results queries are no longer sent to the server, but task queries are, so you end up sending messages without being alerted to the result.

**Comment by sorinpohontu** [comment]
Maybe after a phone restart (see #238) ?

**Comment by ankurverma1994** [comment]
Hey everyone!! I am newbie to open source project. I love coding(prefer JAVA). I want to be active member of any open source project. Can anybody mentor. 
Nowadays I am doing competitive coding. You can view my profile here http://www.codechef.com/users/ankurverma1994
Can anybody mentor me here. #SeriouslyInterested
You may contact me at ankurverma1994@gmail.com

**Comment by eyedol** [comment]
@ankurverma1994 You should go through the issues and let's us know which one you're interested in working on. We will get you started. Also you might want to read the [CONTRIBUTING.md](https://github.com/ushahidi/SMSSync/blob/develop/CONTRIBUTING.md) doc. It has info on how to get started.

**Comment by ankurverma1994** [comment]
Thanks @eyedol for replying. My interest is in Core Java programming. Can you please help me out what to choose and mentor me. I would be very glad if you do so.

**Comment by eyedol** [comment]
@ankurverma1994  I have narrowed down the issues to few ones you can choose from; #252 #235
#218 #246. Let me know which one you are comfortable working on first.

**Comment by eyedol** [comment]
This is related to issue #238. Closing this and tracking the fix there.
