### ISSUE TITLE
SMSSync Interface not displaying on Samsung Galaxy Y, running Android v2.6.3

### ISSUE THREAD

**Issue by aoduor** [ushahidi/SMSSync#254]
Nepal Monitor + Kathmandu living labs team is having trouble using SMSSync v2.8 on the Samsung Galaxy Y, running Android v2.6.3. 

Messages are getting forwarded to the platform,but they are unable to interact with the application's interface on the phone.

**Comment by eyedol** [comment]
Possible to get a screenshot? Thanks

**Comment by Bigdabo** [comment]
Svp aidez moi mon telephone y6 narive pas a syncroniser les sms

**Comment by Bigdabo** [comment]
mon telephone y6 n'arrive pas à syncronisé les sms reçus

**Comment by eyedol** [comment]
Fixed
