### ISSUE TITLE
Task crashed error

### ISSUE THREAD

**Issue by mikeymckay** [ushahidi/SMSSync#255]
During task checking I am getting the following:

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column path $

Here's what my server is responding with:

{"payload":{"task":"send","secret":"coconut","messages":[{"to":"+XXXXXXXX","message":"from couch to you homes","uuid":"aeefa9195f734d32b7e0f9d62d327f6d"}]}}

(XXXXX hides my real number)

Any ideas?

**Comment by eyedol** [comment]
@mikeymckay The sample JSON string looks correct to me and it validates. For some reason a different JSON string gets to the phone when it makes the HTTP GET request. Are you able to debug to see if SMSsync actually receives the above JSON string. Like turn on logs to see if it logs the response. Let me know.

**Comment by mikeymckay** [comment]
@eyedol Thanks for the response. Unfortunately, that IllegalStateException is all that is reported in the logs. It would be useful if the logs showed the http requests and responses, but unless there is a secret option for that somewhere... no dice. Not sure how a different string could get to the phone. I guess I can try testing with some different servers. Here's the relevant part of the ruby sinatra code that serves up the response:

```ruby
get "/smssync" do
  headers "Content-Type" => "application/json; charset=utf8"
  return {
    "payload" => {
      "task" => "send",
      "secret" => "coconut",
      "messages" => messagesToSend
    }
  }.to_json
end

**Comment by eyedol** [comment]
@mikeymckay funky. I just wrote a test to see if sample json string you provided will fail but it did pass. I have added the client response to the logs. You can grab a copy of the debug apk from [here][1]. Let me know what the response you get from the server.

[1]: http://qa.ushahididev.com/job/SMSsync/ws/smssync/build/outputs/apk/smssync-noAnalytics-debug-unaligned.apk

**Comment by mikeymckay** [comment]
I tried the debug apk, but the logs on the app are the same. The adb logcat
isn't really helpful either:

http://pastie.org/10195306

I have a server at http://smssync.zmcp.org which has a message queued for
sending hardcoded right now:

http://smssync.zmcp.org/smssync?task=send

Please try it and see if you have the same result as me?

**Comment by eyedol** [comment]
@mikeymckay Thanks for the link it was helpful. However, I couldn't reproduce the issue on my device( You should get an SMS from a random number). I'm interested in fixing this if it's a unique issue on your device so I have added more logging to get the HTTP response from your device. If you have access to a different Android device, could try to see if the issue shows up on there? Again you can grab a copy of the build from [here][1].

[1]: http://qa.ushahididev.com/job/SMSsync/ws/smssync/build/outputs/apk/smssync-noAnalytics-debug-unaligned.apk
