### ISSUE TITLE
Is it possible to send sms without receiving one?

### ISSUE THREAD

**Issue by dtygel** [ushahidi/SMSSync#269]
Hi all,
    There is something I'm not understanding in SMSSync: When I click in the button "sync" in the "pending messages" dialog, it does not comunicate to the server if there is no message received.Does it mean that SMSSync only checks the server when it has an SMS to send to the server?
    I would like to simply send an SMS message by SMSSync polling regularly to our URL, that would sometime respond to SMSSync with a "send" task, telling SMSSync to send a message. Is it possible? How?

         Thanks,
 
                 daniel tygel

**Comment by eyedol** [comment]
The `Sync` button is for sending failed messages. If the pending list is empty, SMSsync won't contact the server. You have to set a frequency for SMSsync to periodically hit the server to execute the `task`
