### ISSUE TITLE
Scope Ushahidi platform integration

### ISSUE THREAD

**Issue by caharding** [ushahidi/SMSSync#273]

**Comment by eyedol** [comment]
Scope:
SMSsync Integration platform side:
- SMSsync plugin for platform. Should work per the developer documentation; http://smssync.ushahidi.com/developers/
- QR code generator.
- GCM server side support - for sending push notifications.

SMSsync On Android:
- Implement QR code scanner.
- Implement GCM client.

Docs: https://developers.google.com/cloud-messaging/
Drive: https://docs.google.com/document/d/10DH_N-SlC-0kCCKWVUj7Nj8y-LRs0U7Y9XOFVq1pXVQ/edit#
