### ISSUE TITLE
SMSSync not sending SMS when Message Result API is enabled

### ISSUE THREAD

**Issue by anuragsn7** [ushahidi/SMSSync#277]
I have setup SMSSync with my local server with following configuration:

1. SMS Delivery Report `check`
2. Get Reply from Server `check`
3. Enable Auto Sync `check`, frequency `1`
4. Enable Task Checking `check`, frequency `1`
5. Enable Message Result API `check`

In this configuration, SMSSync successfully poll the server link for tasks (`?task=send`), for which I am returning 

```
{
    "payload": {
        "task":"send",
        "secret":"107",
        "messages":
        [
             { 
               "to":"+91<some phone number>",
               "message":"SMSSycn modified test message - 01",
               "uuid":"4ee5667d-6a1d-860c-54d4"
            }
        ]
    }
}
```

the uuid is randomly generated on server. SMSSync is also accessing `?task=sent` and returning following info

```
{"queued_messages":["4ee5667d-6a1d-860c-54d4"]}
```

However, SMSSync is not sending this SMS at all. When `?task=result` is accessed by SMSSync it returns empty data

```
{"message_result":"[]"}
```

But when I uncheck `Message Result API`, SMSSync starts sending SMS. Is there an issue with my configuration? I want to have the SMS delivery report working.

**Comment by eyedol** [comment]
Does the log say anything interesting?
