### ISSUE TITLE
SmsSync

### ISSUE THREAD

**Issue by Hixol** [ushahidi/SMSSync#316]
SmsSync app is not working, sms failed and pending.

**Comment by eyedol** [comment]
@Hixol  need more info. Mind sharing your configurations and the JSON response you send back to SMSsync?

**Comment by Hixol** [comment]
Hello Henry,
Hope you'll be doing good. Thanks for your reply, i have changes the phone
and issue is resolved, app is working and sending messages to a text file
saved on web server, how can i put those messages on map?

On Tue, Aug 11, 2015 at 6:27 PM, Henry Addo <notifications@github.com>
wrote:

> @Hixol <https://github.com/Hixol> need more info. Mind sharing your
> configurations and the JSON response you send back to SMSsync?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/SMSSync/issues/316#issuecomment-129872547>.
>



-- 
Regards,

Imtiaz Ahmed
Manager Marketing
www.hixol.com

**Comment by eyedol** [comment]
What map? An Ushahidi map? if so use the ushahidi's [SMSsync plugin](https://github.com/ushahidi/Ushahidi_Web/tree/develop/plugins/smssync). If it's a custom implementation, I will encourage you look at how you can use Ushahidi as it will be easier.
