### ISSUE TITLE
SmsSync task service

### ISSUE THREAD

**Issue by mapo80** [ushahidi/SMSSync#325]
Hi,

I've found on your repository, could you say me where I can find service class that send sms.

Thanks

**Comment by mapo80** [comment]
I don't know how to find: SyncPendingMessagesService

Thanks

**Comment by eyedol** [comment]
Is [here](https://github.com/ushahidi/SMSSync/blob/legacy-2.x.x/smssync/src/main/java/org/addhen/smssync/services/SyncPendingMessagesService.java)

Moved the 2.x.x code to the [legacy-2.x.x branch](https://github.com/ushahidi/SMSSync/tree/legacy-2.x.x)
