### ISSUE TITLE
Not able to access the current version

### ISSUE THREAD

**Issue by Abhi150688** [ushahidi/SMSSync#330]
Hi, tried to fork the repo & also did a git clone of the existing repo but I am not able to get the current version of the app running (the one which is available on the play store). 
When i compile the code the downloaded code, I get an unstable version 2.8.0

How do i get the most current version?

**Comment by eyedol** [comment]
@Abhi150688 If you want the 2.x.x version then you should build [tag 2.8.3](https://github.com/ushahidi/SMSSync/releases/tag/v2.8.3) or the [legacy-2.x.x branch](https://github.com/ushahidi/SMSSync/tree/legacy-2.x.x). 

You can get compiled APKs from here; https://github.com/ushahidi/SMSSync/releases

**Comment by Abhi150688** [comment]
I need the most recent version and change the sync frequency to 5 seconds instead of a min of 1 minute currently.

**Comment by Abhi150688** [comment]
When i download the source code you mentioned and build i get an error saying:

Error:(173, 0) Cause: repository not found: /Users/Abhishek/Downloads/SMSSync-2.8.3 2
<a href="openFile">Open File</a>

and when I clone your repo then the project build works but it works out to an older version 2.8.0 which is not stable & keeps crashing. 

can you look into it & maybe give me a step by step guide about how I can get a working version 2.8.3..
Or alternatively if you could do me a favour & make the following change in the code & send me the compiled apk for version 2.8.3 
- Change file - TimeUtilFrequency & make the sync period to 5 seconds instead of the minimum supported 1 minute. 

This would be of great help to my project. 
Thanks.

**Comment by eyedol** [comment]
> Error:(173, 0) Cause: repository not found: /Users/Abhishek/Downloads/SMSSync-2.8.3 2
Is this all the error message you get from attempting to build the legacy code? It doesn't tell me much.

**Comment by Abhi150688** [comment]
Yes, when i clone the legacy repo, the build works but i get version 2.8.0
which is very unstable. Whereas when I download the zip file, the build
fails with a gradle error and the above message shows up.

The version that you have on the app store is perfect for us and the best
of all the existing ones. Except that I want to change the sync frequency
to seconds instead of the minimum allowable period of minutes that it
currently supports.

**Comment by eyedol** [comment]
@Abhi150688 This is weird. I'm a bit confused. Which is crashing when you build? The latest master branch or the legacy-2.x.x branch?

We have plans to add seconds support to the frequency times. In future releases this will be supported. You can build the seconds support into the master branch if you really need it.

**Comment by eyedol** [comment]
@Abhi150688 I figured where your compilation error is coming from. It's because you downloaded the code as a zip file. We use git commits to provid automatic version numbers. When you download as a zip archive, you don't have the repo. Try to clone it instead. 

I'll put a note in the read me file.

**Comment by Abhi150688** [comment]
I tried cloning
a) Master Branch
b) tag 2.8.3
c) legacy branch

But even on cloning, when i run the app, i end up with version 2.8.0.

Somehow, I am not able to get to the version that you guys have available
on the play store. I want the play store version where I can edit the
frequency.

**Comment by eyedol** [comment]
@Abhi150688 If building from Android Studio is failing, trying the command line. I'm also suspecting you'll have to upgrade or install some missing build tools. Android studio should prompt you to install those if they're missing.

``` ./gradlew --stacktrace build ```

The `stacktrace` flag should give us more info

If these doesn't yield any headway, I'm not sure what's going on.

**Comment by Abhi150688** [comment]
You are not getting the issue.

Everything is working fine the app runs on the phone when I build using
android studio but I don't get the current version of the app the app
builds to version 2.8.0

Here is the attached snapshot of the app that I get on my phone when I
clone the master branch

It's version 2.8.0. I am not able to get version 2.8.3

I have tried cloning the legacy branch the branch 2.8.3 and the master
branch but every time I compile I get the same 2.8.0 version

**Comment by eyedol** [comment]
The tag [tag 2.8.3](https://github.com/ushahidi/SMSSync/releases/tag/v2.8.3) should be the one on the app store. If you've successfully built it and it's still showing v2.8.0 then the automatic versioning is screwing up something.  should be the current version on the app store.

The master branch has been built on the legacy branch. Once I increase the version, it will change. The upcoming version would be v3.0.0. Right now it hasn't been increased that is why you still see v2.8.0.

**Comment by Abhi150688** [comment]
Okay.

I had another query.
a) Can the polling frequency be set to 5 seconds. Where the app will poll
the server every 5 seconds to check if there are any pending jobs (messages
to be sent).

b) Alternatively since this could be a resource draining move. Can the
server send a push to the app whenever there is a new job to be executed.

The reason for this is that I am looking for real time messaging. I cannot
have the customer wait 1 minute before receiving a reply to his message.

**Comment by eyedol** [comment]
@Abhi150688 There is an issue to revisit the time picker and possibly add seconds support. See #327 

Sending push notification requires work on both the server side and SMSsync. There is an issue to support GCM for push notifications #268 

If you've bandwidth, you're free to pick up any of these. We've interest in implementing them.
