### ISSUE TITLE
Make Way For  A Release

### ISSUE THREAD

**Issue by eyedol** [ushahidi/SMSSync#333]
Now that we've reached 3.0.0 feature set, go through the app to fix all obvious bugs. This should be in the release branch.

Update change log, 
Increase version number, tag and push to playstore.

**Comment by salman643229** [comment]
[Gqqggahu](url)hshHahqhfajw
Hajsyava
Sg.saiya
Suhjwwhi1gw
Vahaogfuwjwg
Hai susu sujwbfsiflbvawtwnz
Vwjhwwippqqm bf ckgs
Lskvssissusjs
Nk we bhqhhqnajwuwgw
Ojewjakhqjekzh
