### ISSUE TITLE
Version 3 is not make any requests to the server, can`t set intervals

### ISSUE THREAD

**Issue by Warloxk** [ushahidi/SMSSync#339]
I tried the example php script in the documentation, but it got error 500 on a server, then an another server i successfully ran the script, but the android app it says "not have a valid endpoint" (or something like that)

Then i wrote a script that don`t do anyithing just make a "success" answer for the app, this is working and the app says "it is a valid endpoint", but not working the fetch new messages.

So i make a script that logs every request that it received, but the logs only have entries when i test the endpoint in the "integrations" settings. No entry for the "fetch new messages" or anything else.

And in the settings there is a option to set the interval for some actions, but that window where i can pick a time, i only have hours and minutes, and only "cancel" button, so i can`t set that value. If i "click" outside of the window, it disappear, but not set the value.

The previous version what i found on the f-droid, it is working fine (2.7.3) and i can set the intervals, and this version is actually made requests to the server.

**Comment by eyedol** [comment]
Funky. I'll take a look at this and make a fix real quick. Thanks for the bug report.
