### ISSUE TITLE
Website menu on mobil device can`t "clicked"

### ISSUE THREAD

**Issue by Warloxk** [ushahidi/SMSSync#340]
Website (http://smssync.ushahidi.com/) menu on mobil device can`t "clicked" because of the "fork me on github" sticker.

**Comment by eyedol** [comment]
@Warloxk are you experiencing this on a really small device? Because it looks good on a nexus 6 device. I'll look into it.

**Comment by Warloxk** [comment]
@eyedol on Galaxy Tab 2 7.0, attached a screenshot too.
![smssync](https://cloud.githubusercontent.com/assets/8527687/10669674/1e8551be-78e2-11e5-9737-cb573e0949a5.jpg)
