### ISSUE TITLE
many problem in version 3.0.2

### ISSUE THREAD

**Issue by 9px** [ushahidi/SMSSync#341]
1) i enable Log, but i cant see full detail log like old version (2.8)

2) "delete all" doesn't work for clear log

3) when i set `Data Format` to `JSON` in `Add/Update custom web service`, it is not saved!

4) when i want to delete a `custom web service` i see an error that says it is enabled, but i cant disable it!

5) there are some difference between `smssync.ushahidi.com/developers` and what the app sent. for example the phrase `SMS Delivered` appear as `SMS delivered` in the response. Also `sent_result_code` and `delivered_result_code` is ambiguous. i get `SMS Delivered` message with different `delivered_result_code` code.

**Comment by levisdoban** [comment]
I agree, version 3.0.2 is messed up. Had to move back to v. 2.7.3 ... and still a few issues there.

**Comment by eyedol** [comment]
@9px Mind sharing a screen shot for issue 2 " i enable Log, but i cant see full detail log like old version (2.8)" I see the log entries.

Delete all seems to work for me.

**Comment by eyedol** [comment]
@9px What's the `delivered_result_code` is? Those are dished by the OS. We don't control over that.

**Comment by 9px** [comment]
in last version, the 3th problem remain unsolved!
when i set `Data Format` to `JSON` in `Add/Update custom web service`, does not save after click `update`!
