### ISSUE TITLE
Confirm/clarify sent_timestamp placeholder being POST-ed

### ISSUE THREAD

**Issue by siddhartham-ysg** [ushahidi/SMSSync#343]
The developer docs say this about *sent_timestamp*:

>sent_timestamp -- the timestamp the SMS was sent. In the UNIX timestamp format

What was expected is that: that this is the unix time-stamp when the SMS was received, however as it happens to be the time-stamp is when the SMS is being relayed to or POST-ed to an URL/I for the application I am building?

What should be the expected/appropriate behaviour? Is what i am facing appropriate behaviour?

**Comment by eyedol** [comment]
@siddhartham-ysg It's the timestamp when the SMS was sent to the phone. In other words when it was received. The timestamp is not when it was posted to the server.

**Comment by siddhartham-ysg** [comment]
@eyedol thanks for clarifying!

**Comment by eyedol** [comment]
@siddhartham-ysg :+1:  Let me know if it's showing otherwise.

**Comment by siddhartham-ysg** [comment]
@eyedol In the past few weeks certain circumstances we were inclined to infer this, it could really be an observational anomaly; today we checked the behaviour again and it worked out as you have mentioned.
