### ISSUE TITLE
App sends data of all failed messages in one request

### ISSUE THREAD

**Issue by RaghavPro** [ushahidi/SMSSync#356]
Let's say I have one pending message. I try to publish it. My service does not respond with JSON so it goes back to pending again. 
Now if I try to publish again it increments the data of all the failed messages with that request.
For example
```
secret=test&from=%2B919810956505&message=send-sms%20DL%20asdf&sent_timestamp=1447780978323&sent_to=%2B919810956505&message_id=b8710e7d-307b-4263-9c48-9d7e9e1349b4&device_id=&
secret=test&from=%2B919810956505&message=send-sms%20DL%20asdf&sent_timestamp=1447780978323&sent_to=%2B919810956505&message_id=b8710e7d-307b-4263-9c48-9d7e9e1349b4&device_id=&
secret=test&from=%2B919810956505&message=send-sms%20DL%20asdf&sent_timestamp=1447780978323&sent_to=%2B919810956505&message_id=1825f01b-b313-4db8-b6b2-66eed4123582&device_id=
```

This happens only when I choose <b>URLEncoded</b> or <b>XML</b> as data format for my request. JSON works fine and only sends data of that one message I selected.

**Comment by eyedol** [comment]
@RaghavPro Funky. Thanks for reporting. Will look into this.

**Comment by RaghavPro** [comment]
Another thing which is very weird. 
I have two services. One is heroku and the other is http://requestb.in, which inspect http requests.
They both have different secret keys.

But, I see secret key of heroku service on requestb page along with requestb's secret key.

Request body:
```secret=test&from=%2B919810956505&message=send-sms%20DL%20asdf&sent_timestamp=1447780978323&sent_to=%2B919810956505&message_id=cfbb54c5-3ef6-4a90-8182-efadc225f94b&device_id=&
secret=test&from=%2B919810956505&message=send-sms%20DL%20asdf&sent_timestamp=1447780978323&sent_to=%2B919810956505&message_id=5a3097df-cb3e-47e3-bfaa-0034a7fdbaff&device_id=&
secret=w%2Fx1fY%3F%2Fxc2S&from=%2B919810956505&message=send-sms%20DL%20asdf&sent_timestamp=1447780978323&sent_to=%2B919810956505&message_id=cfbb54c5-3ef6-4a90-8182-efadc225f94b&device_id=&
secret=w%2Fx1fY%3F%2Fxc2S&from=%2B919810956505&message=send-sms%20DL%20asdf&sent_timestamp=1447780978323&sent_to=%2B919810956505&message_id=5a3097df-cb3e-47e3-bfaa-0034a7fdbaff&device_id=
```

Here's a screenshot from requestb's page for better readability.
![screen shot 2015-11-18 at 23 03 16](https://cloud.githubusercontent.com/assets/4872139/11248708/b39f1be2-8e48-11e5-948e-ba9ce45adee2.png)

test is for requestb and the other one is for heroku.

It is sending details of one service with the url of another. Weird. This is all from one request.

**Comment by eyedol** [comment]
@RaghavPro Quick question. We're you manually publishing the failed messages? You hit a button to upload the messages.

**Comment by RaghavPro** [comment]
Yes, manually published it.
________________________________
