### ISSUE TITLE
'sent_to' parameter only contains the 'from' values

### ISSUE THREAD

**Issue by redbullpeter** [ushahidi/SMSSync#362]
According to the API details the 'sent_to' should contain "the phone number registered on the SIM card otherwise it's the value set on the app as device ID"

However we're seeing that the 'sent_to' parameter always contains the 'from' values.

SMSsync v3.0.4

Handsets tested:

Samsung GT-I9060I Android// 4.4.4
Xolo Q1010i Android 4.4.2

**Comment by siddhartham-ysg** [comment]
@ushahidi:

This issue still persists.
We are running v2.8.3 (Micromax-Q3372/ Android: 5.0) and this seems to be ok once you set the phone number on the SIM.
However, v3.0.4 (Samsung-SMG355H / Android: 4.4.2) still has this problem wherein the sent_to value is being picked up from the from field instead. We weren't able to downgrade the SMSSync app, so couldn't isolate the exact problem area.
Can you confirm this? Please, help us out with this!
