### ISSUE TITLE
can't fetch new messages from inbox

### ISSUE THREAD

**Issue by rm2k** [ushahidi/SMSSync#369]
![screenshot_2016-01-27-12-46-56](https://cloud.githubusercontent.com/assets/1936364/12613514/eb4d33b2-c502-11e5-861c-80f773270b06.png)

**Comment by zhil** [comment]
+1
the same thing on v3.0.4, tried on 2 different phones. 
Added web handlers, tested it, it works (however it sends only secret in test mode, no other vars).
Activated as default sms programm, but it just dont work. Nothing in logs. The same error as on upper screenshot.

**Comment by zhil** [comment]
@rm2k tried v3.0.3 from [builds list](https://github.com/ushahidi/SMSSync/releases) - it works for me

@eyedol it would be great if you will have chance to check it, it should be simple bug between 3.0.3 and 3.0.4

**Comment by ar2oor** [comment]
Same here.
![20161038103831](https://cloud.githubusercontent.com/assets/1141686/12928123/0632e2da-cf6c-11e5-88f4-1b81f0cf1eea.jpg)
