### ISSUE TITLE
SMSSync capitalisation is inconsistent

### ISSUE THREAD

**Issue by alxndrsn** [ushahidi/SMSSync#379]
Just wondering which is correct:

1. SMSSync, or
2. SMSsync

**Comment by mandric** [comment]
From what I gather the "marketing" or published name is SMSsync, the proper camel caps (code) spelling is SMSSync.

**Comment by eyedol** [comment]
Correct with @mandric comment. We changed the name from `SMSSync` to `SMSsync`

**Comment by alxndrsn** [comment]
:+1:
