### ISSUE TITLE
Why is READ_PHONE_STATE permission requested?

### ISSUE THREAD

**Issue by alxndrsn** [ushahidi/SMSSync#415]
The only method I can see that is called which might require this permission is [`TelephonyManager.getLine1Number()`](https://developer.android.com/reference/android/telephony/TelephonyManager.html#getLine1Number%28%29).  However, from the docs linked, this will also be happy with the `READ_SMS` permission, which SMSSync also requests.

**Comment by eyedol** [comment]
I'm sure this is coming for copy and paste from old code in the past.
