### ISSUE TITLE
how can i able send message SMS from server ?

### ISSUE THREAD

**Issue by acan12** [ushahidi/SMSSync#444]

**Comment by azerafati** [comment]
yeah, it would have been so great if the app could periodically check the server like calling a web-service, and in case there was a response send it as a SMS.
I've worked with [this app](https://play.google.com/store/apps/details?id=eu.apksoft.android.smsgateway&hl=en) which has a similar feature by checking a mail box by pop3 and sending the mails as SMS, the subject should be a number and the body is send as the msg
