### ISSUE TITLE
Single Message getting published multiple times

### ISSUE THREAD

**Issue by aoduor** [ushahidi/SMSSync#461]
Received three complaints so far about SMSSync publishing a single message multiple times on syncing.

Flagging this as an urgent P0 Bug

**Comment by aoduor** [comment]
Related to #454

**Comment by gthuo** [comment]
Getting this issue too. Becomes a nightmare.

**Comment by VinceMukiiri** [comment]
Still encountering this issue

**Comment by gthuo** [comment]
Has the issue been resolved?

**Comment by aoduor** [comment]
Hey @gthuo, there's a new release of smssync on the playstore, please download and let us know if you face any problems
